-- BulletAI all-in-one schema setup and repair script.
-- Run this single file in Supabase SQL Editor.
-- It is safe for both a fresh project and a project that already has older BulletAI tables.

-- 1. Base tables

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.moments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.reflections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

-- 2. Repair/upgrade columns for existing old tables

alter table public.profiles
  add column if not exists username text,
  add column if not exists preferred_language text not null default 'zh',
  add column if not exists ui_theme text not null default 'calm',
  add column if not exists accent_color text not null default 'sage',
  add column if not exists color_scheme text not null default 'system',
  add column if not exists completed_goal_retention text not null default 'next_day',
  add column if not exists username_updated_at timestamptz,
  add column if not exists preferences_updated_at timestamptz,
  add column if not exists created_at timestamptz default timezone('utc'::text, now()),
  add column if not exists updated_at timestamptz default timezone('utc'::text, now());

alter table public.moments
  add column if not exists client_id text,
  add column if not exists image_path text,
  add column if not exists created_at timestamptz default timezone('utc'::text, now()),
  add column if not exists updated_at timestamptz default timezone('utc'::text, now()),
  add column if not exists deleted_at timestamptz;

alter table public.reflections
  add column if not exists client_id text,
  add column if not exists title text,
  add column if not exists body text,
  add column if not exists source text,
  add column if not exists source_type text,
  add column if not exists location text,
  add column if not exists image_path text,
  add column if not exists created_at timestamptz default timezone('utc'::text, now()),
  add column if not exists updated_at timestamptz default timezone('utc'::text, now()),
  add column if not exists deleted_at timestamptz;

alter table public.goals
  add column if not exists client_id text,
  add column if not exists description text,
  add column if not exists status text,
  add column if not exists due_date date,
  add column if not exists progress int,
  add column if not exists color text,
  add column if not exists sort_order double precision,
  add column if not exists image_path text,
  add column if not exists created_at timestamptz default timezone('utc'::text, now()),
  add column if not exists updated_at timestamptz default timezone('utc'::text, now()),
  add column if not exists deleted_at timestamptz;

alter table public.habits
  add column if not exists client_id text,
  add column if not exists description text,
  add column if not exists frequency text,
  add column if not exists color text,
  add column if not exists last_checkin timestamptz,
  add column if not exists checkin_count int,
  add column if not exists created_at timestamptz default timezone('utc'::text, now()),
  add column if not exists updated_at timestamptz default timezone('utc'::text, now()),
  add column if not exists deleted_at timestamptz;

-- Drop old check constraints before data cleanup.
-- Existing projects may have constraints that reject the normalized values below.

alter table public.profiles drop constraint if exists profiles_preferred_language_check;
alter table public.profiles drop constraint if exists profiles_ui_theme_check;
alter table public.profiles drop constraint if exists profiles_accent_color_check;
alter table public.profiles drop constraint if exists profiles_color_scheme_check;
alter table public.profiles drop constraint if exists profiles_completed_goal_retention_check;
alter table public.goals drop constraint if exists goals_status_check;
alter table public.goals drop constraint if exists goals_progress_check;
alter table public.habits drop constraint if exists habits_frequency_check;

-- 3. Normalize existing old data before constraints

update public.profiles
set
  username = nullif(btrim(username), ''),
  preferred_language = case when preferred_language in ('zh', 'en') then preferred_language else 'zh' end,
  ui_theme = 'calm',
  accent_color = case when accent_color in ('sage', 'green', 'purple', 'amber') then accent_color else 'sage' end,
  color_scheme = case when color_scheme in ('system', 'light', 'dark') then color_scheme else 'system' end,
  completed_goal_retention = case
    when completed_goal_retention in ('instant', 'next_day', 'never') then completed_goal_retention
    else 'next_day'
  end,
  username_updated_at = coalesce(username_updated_at, updated_at),
  created_at = coalesce(created_at, timezone('utc'::text, now())),
  updated_at = coalesce(updated_at, timezone('utc'::text, now()))
where true;

with ranked_usernames as (
  select
    ctid,
    row_number() over (
      partition by lower(username)
      order by updated_at desc nulls last, created_at desc nulls last, user_id
    ) as row_number
  from public.profiles
  where username is not null
)
update public.profiles profiles
set username = null
from ranked_usernames
where profiles.ctid = ranked_usernames.ctid
  and ranked_usernames.row_number > 1;

update public.moments
set
  client_id = coalesce(nullif(client_id, ''), 'moment-' || id::text),
  created_at = coalesce(created_at, timezone('utc'::text, now())),
  updated_at = coalesce(updated_at, created_at, timezone('utc'::text, now()))
where true;

update public.reflections
set
  client_id = coalesce(nullif(client_id, ''), 'reflection-' || id::text),
  title = coalesce(
    nullif(title, ''),
    case
      when position(E'\n\n' in content) > 0 and char_length(split_part(content, E'\n\n', 1)) <= 100
        then nullif(split_part(content, E'\n\n', 1), '')
      else null
    end
  ),
  body = coalesce(
    nullif(body, ''),
    case
      when position(E'\n\n' in content) > 0 and char_length(split_part(content, E'\n\n', 1)) <= 100
        then nullif(substring(content from position(E'\n\n' in content) + 2), '')
      else content
    end
  ),
  created_at = coalesce(created_at, timezone('utc'::text, now())),
  updated_at = coalesce(updated_at, created_at, timezone('utc'::text, now()))
where true;

update public.goals
set
  client_id = coalesce(nullif(client_id, ''), 'goal-' || id::text),
  description = coalesce(description, ''),
  status = case when status in ('pending', 'default', 'completed') then status else 'pending' end,
  progress = least(greatest(coalesce(progress, 0), 0), 100),
  sort_order = coalesce(sort_order, -extract(epoch from coalesce(created_at, timezone('utc'::text, now())))),
  created_at = coalesce(created_at, timezone('utc'::text, now())),
  updated_at = coalesce(updated_at, created_at, timezone('utc'::text, now()))
where true;

update public.habits
set
  client_id = coalesce(nullif(client_id, ''), 'habit-' || id::text),
  frequency = case
    when frequency in ('weekly', 'Weekly', '每周') then 'weekly'
    else 'daily'
  end,
  checkin_count = coalesce(checkin_count, 0),
  created_at = coalesce(created_at, timezone('utc'::text, now())),
  updated_at = coalesce(updated_at, created_at, timezone('utc'::text, now()))
where true;

-- 4. Align column types/defaults/nullability

alter table public.profiles
  alter column username drop not null,
  alter column preferred_language set default 'zh',
  alter column preferred_language set not null,
  alter column ui_theme set default 'calm',
  alter column ui_theme set not null,
  alter column accent_color set default 'sage',
  alter column accent_color set not null,
  alter column color_scheme set default 'system',
  alter column color_scheme set not null,
  alter column completed_goal_retention set default 'next_day',
  alter column completed_goal_retention set not null,
  alter column created_at type timestamptz using created_at::timestamptz,
  alter column created_at set default timezone('utc'::text, now()),
  alter column created_at set not null,
  alter column updated_at type timestamptz using updated_at::timestamptz,
  alter column updated_at set default timezone('utc'::text, now()),
  alter column updated_at set not null;

alter table public.moments
  alter column created_at type timestamptz using created_at::timestamptz,
  alter column created_at set default timezone('utc'::text, now()),
  alter column created_at set not null,
  alter column updated_at type timestamptz using updated_at::timestamptz,
  alter column updated_at set default timezone('utc'::text, now()),
  alter column updated_at set not null,
  alter column client_id set not null;

alter table public.reflections
  alter column created_at type timestamptz using created_at::timestamptz,
  alter column created_at set default timezone('utc'::text, now()),
  alter column created_at set not null,
  alter column updated_at type timestamptz using updated_at::timestamptz,
  alter column updated_at set default timezone('utc'::text, now()),
  alter column updated_at set not null,
  alter column client_id set not null;

alter table public.goals
  alter column description set default '',
  alter column description set not null,
  alter column status set default 'pending',
  alter column status set not null,
  alter column progress set default 0,
  alter column progress set not null,
  alter column created_at type timestamptz using created_at::timestamptz,
  alter column created_at set default timezone('utc'::text, now()),
  alter column created_at set not null,
  alter column updated_at type timestamptz using updated_at::timestamptz,
  alter column updated_at set default timezone('utc'::text, now()),
  alter column updated_at set not null,
  alter column client_id set not null;

alter table public.habits
  alter column frequency set default 'daily',
  alter column frequency set not null,
  alter column checkin_count set default 0,
  alter column checkin_count set not null,
  alter column created_at type timestamptz using created_at::timestamptz,
  alter column created_at set default timezone('utc'::text, now()),
  alter column created_at set not null,
  alter column updated_at type timestamptz using updated_at::timestamptz,
  alter column updated_at set default timezone('utc'::text, now()),
  alter column updated_at set not null,
  alter column client_id set not null;

-- 5. Habit check-in history

create table if not exists public.habit_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  habit_id bigint not null references public.habits(id) on delete cascade,
  checked_on date not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.habit_checkins
  add column if not exists user_id uuid,
  add column if not exists habit_id bigint,
  add column if not exists checked_on date,
  add column if not exists created_at timestamptz default timezone('utc'::text, now());

alter table public.habit_checkins
  alter column created_at type timestamptz using created_at::timestamptz,
  alter column created_at set default timezone('utc'::text, now()),
  alter column created_at set not null;

insert into public.habit_checkins (user_id, habit_id, checked_on, created_at)
select
  user_id,
  id,
  last_checkin::date,
  coalesce(last_checkin, timezone('utc'::text, now()))
from public.habits
where last_checkin is not null
on conflict do nothing;

delete from public.habit_checkins a
using public.habit_checkins b
where a.id > b.id
  and a.user_id = b.user_id
  and a.habit_id = b.habit_id
  and a.checked_on = b.checked_on;

-- 6. Constraints

alter table public.profiles drop constraint if exists profiles_preferred_language_check;
alter table public.profiles
  add constraint profiles_preferred_language_check
  check (preferred_language in ('zh', 'en'));

alter table public.profiles drop constraint if exists profiles_ui_theme_check;
alter table public.profiles
  add constraint profiles_ui_theme_check
  check (ui_theme in ('calm'));

alter table public.profiles drop constraint if exists profiles_accent_color_check;
alter table public.profiles
  add constraint profiles_accent_color_check
  check (accent_color in ('sage', 'green', 'purple', 'amber'));

alter table public.profiles drop constraint if exists profiles_color_scheme_check;
alter table public.profiles
  add constraint profiles_color_scheme_check
  check (color_scheme in ('system', 'light', 'dark'));

alter table public.profiles drop constraint if exists profiles_completed_goal_retention_check;
alter table public.profiles
  add constraint profiles_completed_goal_retention_check
  check (completed_goal_retention in ('instant', 'next_day', 'never'));

alter table public.goals drop constraint if exists goals_status_check;
alter table public.goals
  add constraint goals_status_check
  check (status in ('pending', 'default', 'completed'));

alter table public.goals drop constraint if exists goals_progress_check;
alter table public.goals
  add constraint goals_progress_check
  check (progress >= 0 and progress <= 100);

alter table public.habits drop constraint if exists habits_frequency_check;
alter table public.habits
  add constraint habits_frequency_check
  check (frequency in ('daily', 'weekly'));

alter table public.habit_checkins drop constraint if exists habit_checkins_user_habit_day_unique;
alter table public.habit_checkins
  add constraint habit_checkins_user_habit_day_unique
  unique (user_id, habit_id, checked_on);

-- 7. Indexes

create unique index if not exists profiles_username_idx on public.profiles(username);
create index if not exists profiles_user_id_idx on public.profiles(user_id);
create index if not exists moments_user_id_idx on public.moments(user_id);
create unique index if not exists moments_client_id_idx on public.moments(client_id);
create index if not exists reflections_user_id_idx on public.reflections(user_id);
create unique index if not exists reflections_client_id_idx on public.reflections(client_id);
create index if not exists goals_user_id_idx on public.goals(user_id);
create unique index if not exists goals_client_id_idx on public.goals(client_id);
create index if not exists goals_user_due_date_idx on public.goals(user_id, due_date);
create index if not exists goals_user_sort_order_idx on public.goals(user_id, sort_order);
create index if not exists habits_user_id_idx on public.habits(user_id);
create unique index if not exists habits_client_id_idx on public.habits(client_id);
create index if not exists habit_checkins_user_checked_on_idx
  on public.habit_checkins(user_id, checked_on desc);
create index if not exists habit_checkins_habit_checked_on_idx
  on public.habit_checkins(habit_id, checked_on desc);

-- AI usage events for lightweight per-user rate limiting.

create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists ai_usage_events_user_created_at_idx
  on public.ai_usage_events(user_id, created_at desc);

-- 8. updated_at trigger

create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists update_profiles_updated_at on public.profiles;
create trigger update_profiles_updated_at
  before update on public.profiles
  for each row
  execute function public.update_updated_at_column();

drop trigger if exists update_moments_updated_at on public.moments;
create trigger update_moments_updated_at
  before update on public.moments
  for each row
  execute function public.update_updated_at_column();

drop trigger if exists update_reflections_updated_at on public.reflections;
create trigger update_reflections_updated_at
  before update on public.reflections
  for each row
  execute function public.update_updated_at_column();

drop trigger if exists update_goals_updated_at on public.goals;
create trigger update_goals_updated_at
  before update on public.goals
  for each row
  execute function public.update_updated_at_column();

drop trigger if exists update_habits_updated_at on public.habits;
create trigger update_habits_updated_at
  before update on public.habits
  for each row
  execute function public.update_updated_at_column();

-- 9. Row Level Security

alter table public.profiles enable row level security;
alter table public.moments enable row level security;
alter table public.reflections enable row level security;
alter table public.goals enable row level security;
alter table public.habits enable row level security;
alter table public.habit_checkins enable row level security;
alter table public.ai_usage_events enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
  on public.profiles for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can select own moments" on public.moments;
create policy "Users can select own moments"
  on public.moments for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own moments" on public.moments;
create policy "Users can insert own moments"
  on public.moments for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own moments" on public.moments;
create policy "Users can update own moments"
  on public.moments for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own moments" on public.moments;
create policy "Users can delete own moments"
  on public.moments for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can select own reflections" on public.reflections;
create policy "Users can select own reflections"
  on public.reflections for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own reflections" on public.reflections;
create policy "Users can insert own reflections"
  on public.reflections for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own reflections" on public.reflections;
create policy "Users can update own reflections"
  on public.reflections for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own reflections" on public.reflections;
create policy "Users can delete own reflections"
  on public.reflections for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can select own goals" on public.goals;
create policy "Users can select own goals"
  on public.goals for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own goals" on public.goals;
create policy "Users can insert own goals"
  on public.goals for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own goals" on public.goals;
create policy "Users can update own goals"
  on public.goals for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own goals" on public.goals;
create policy "Users can delete own goals"
  on public.goals for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can select own habits" on public.habits;
create policy "Users can select own habits"
  on public.habits for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own habits" on public.habits;
create policy "Users can insert own habits"
  on public.habits for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own habits" on public.habits;
create policy "Users can update own habits"
  on public.habits for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own habits" on public.habits;
create policy "Users can delete own habits"
  on public.habits for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can select own habit checkins" on public.habit_checkins;
create policy "Users can select own habit checkins"
  on public.habit_checkins for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own habit checkins" on public.habit_checkins;
create policy "Users can insert own habit checkins"
  on public.habit_checkins for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own habit checkins" on public.habit_checkins;
create policy "Users can delete own habit checkins"
  on public.habit_checkins for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can select own AI usage events" on public.ai_usage_events;
create policy "Users can select own AI usage events"
  on public.ai_usage_events for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own AI usage events" on public.ai_usage_events;
create policy "Users can insert own AI usage events"
  on public.ai_usage_events for insert
  with check (auth.uid() = user_id);

-- 10. Storage buckets and policies

insert into storage.buckets (id, name, public)
values
  ('moments', 'moments', false),
  ('reflections', 'reflections', false),
  ('goals', 'goals', false),
  ('habits', 'habits', false)
on conflict (id) do nothing;

drop policy if exists "Users can read own stored files" on storage.objects;
create policy "Users can read own stored files"
  on storage.objects for select
  using (
    bucket_id in ('moments', 'reflections', 'goals', 'habits')
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Users can upload own stored files" on storage.objects;
create policy "Users can upload own stored files"
  on storage.objects for insert
  with check (
    bucket_id in ('moments', 'reflections', 'goals', 'habits')
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Users can update own stored files" on storage.objects;
create policy "Users can update own stored files"
  on storage.objects for update
  using (
    bucket_id in ('moments', 'reflections', 'goals', 'habits')
    and auth.uid()::text = (storage.foldername(name))[1]
  )
  with check (
    bucket_id in ('moments', 'reflections', 'goals', 'habits')
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Users can delete own stored files" on storage.objects;
create policy "Users can delete own stored files"
  on storage.objects for delete
  using (
    bucket_id in ('moments', 'reflections', 'goals', 'habits')
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- 11. Refresh Supabase/PostgREST schema cache

notify pgrst, 'reload schema';
