-- BulletAI database schema.
--
-- This file is the single initialization entry point for a Supabase project.

-- Core tables -----------------------------------------------------------------

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text,
  preferred_language text not null default 'zh'
    check (preferred_language in ('zh', 'en')),
  accent_color text not null default 'sage'
    check (accent_color in ('sage', 'green', 'purple', 'amber')),
  color_scheme text not null default 'system'
    check (color_scheme in ('system', 'light', 'dark')),
  completed_goal_retention text not null default 'next_day'
    check (completed_goal_retention in ('instant', 'next_day', 'never')),
  week_starts_on text not null default 'auto'
    check (week_starts_on in ('auto', 'monday', 'sunday', 'saturday')),
  version bigint not null default 1 check (version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_not_blank
    check (username is null or btrim(username) <> '')
);

create table public.moments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  content text not null check (btrim(content) <> ''),
  occurred_on date not null default current_date,
  image_path text,
  version bigint not null default 1 check (version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint moments_user_client_id_unique unique (user_id, client_id),
  constraint moments_client_id_not_blank check (btrim(client_id) <> '')
);

create table public.reflections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  title text not null check (btrim(title) <> ''),
  body text not null check (btrim(body) <> ''),
  version bigint not null default 1 check (version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reflections_user_client_id_unique unique (user_id, client_id),
  constraint reflections_client_id_not_blank check (btrim(client_id) <> '')
);

create table public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  title text not null check (btrim(title) <> ''),
  description text not null default '',
  due_date date,
  color text,
  sort_order double precision not null default 0,
  completed_at timestamptz,
  version bigint not null default 1 check (version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint goals_user_client_id_unique unique (user_id, client_id),
  constraint goals_client_id_not_blank check (btrim(client_id) <> '')
);

create table public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  name text not null check (btrim(name) <> ''),
  description text,
  frequency text not null default 'daily'
    check (frequency in ('daily', 'weekly')),
  color text,
  started_on date not null,
  version bigint not null default 1 check (version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint habits_user_client_id_unique unique (user_id, client_id),
  constraint habits_client_id_not_blank check (btrim(client_id) <> '')
);

create table public.habit_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  habit_id bigint not null references public.habits(id) on delete cascade,
  habit_client_id text not null,
  checked_on date not null,
  version bigint not null default 1 check (version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint habit_checkins_user_client_id_unique unique (user_id, client_id),
  constraint habit_checkins_user_habit_day_unique
    unique (user_id, habit_client_id, checked_on),
  constraint habit_checkins_habit_client_id_fkey
    foreign key (user_id, habit_client_id)
    references public.habits(user_id, client_id) on delete cascade,
  constraint habit_checkins_client_id_not_blank check (btrim(client_id) <> '')
);

create table public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.workspace_change_log (
  sequence bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  resource text not null check (
    resource in (
      'profiles',
      'moments',
      'reflections',
      'goals',
      'habits',
      'habit_checkins'
    )
  ),
  client_id text not null check (btrim(client_id) <> ''),
  operation text not null check (operation in ('upsert', 'delete')),
  version bigint not null check (version >= 1),
  changed_at timestamptz not null default now()
);

-- Keep the one-to-one auth/profile invariant at the database boundary.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

revoke all on function public.handle_new_user()
  from public, anon, authenticated;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Domain invariants and optimistic-concurrency triggers -----------------------

create or replace function public.resolve_habit_checkin_reference()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  resolved_habit_id bigint;
  resolved_client_id text;
begin
  if new.habit_client_id is not null then
    select id, client_id
      into resolved_habit_id, resolved_client_id
    from public.habits
    where user_id = new.user_id
      and client_id = new.habit_client_id;
  elsif new.habit_id is not null then
    select id, client_id
      into resolved_habit_id, resolved_client_id
    from public.habits
    where user_id = new.user_id
      and id = new.habit_id;
  end if;

  if resolved_habit_id is null then
    raise foreign_key_violation using
      message = 'Habit check-in must reference a habit owned by the same user';
  end if;

  new.habit_id = resolved_habit_id;
  new.habit_client_id = resolved_client_id;
  return new;
end;
$$;

revoke all on function public.resolve_habit_checkin_reference()
  from public, anon, authenticated;

create trigger resolve_habit_checkin_reference
  before insert or update of user_id, habit_id, habit_client_id
  on public.habit_checkins
  for each row execute function public.resolve_habit_checkin_reference();

create or replace function public.enforce_habit_started_on_immutable()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.started_on is distinct from old.started_on then
    raise check_violation using
      message = 'Habit started_on is immutable';
  end if;
  return new;
end;
$$;

revoke all on function public.enforce_habit_started_on_immutable()
  from public, anon, authenticated;

create trigger enforce_habit_started_on_immutable
  before update of started_on on public.habits
  for each row execute function public.enforce_habit_started_on_immutable();

create or replace function public.advance_entity_version()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.version = old.version + 1;
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.advance_entity_version()
  from public, anon, authenticated;

create trigger advance_profiles_version
  before update on public.profiles
  for each row execute function public.advance_entity_version();
create trigger advance_moments_version
  before update on public.moments
  for each row execute function public.advance_entity_version();
create trigger advance_reflections_version
  before update on public.reflections
  for each row execute function public.advance_entity_version();
create trigger advance_goals_version
  before update on public.goals
  for each row execute function public.advance_entity_version();
create trigger advance_habits_version
  before update on public.habits
  for each row execute function public.advance_entity_version();
create trigger advance_habit_checkins_version
  before update on public.habit_checkins
  for each row execute function public.advance_entity_version();

-- Record durable incremental-sync changes after each committed domain write.
create or replace function public.record_workspace_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  row_data jsonb := case
    when tg_op = 'DELETE' then to_jsonb(old)
    else to_jsonb(new)
  end;
  owner_id uuid := (row_data ->> 'user_id')::uuid;
  stable_client_id text;
  entity_version bigint := (row_data ->> 'version')::bigint;
begin
  stable_client_id := case
    when tg_table_name = 'profiles' then owner_id::text
    else row_data ->> 'client_id'
  end;

  if not exists (
    select 1 from auth.users where id = owner_id
  ) then
    return case when tg_op = 'DELETE' then old else new end;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'workspace_change_log:' || owner_id::text,
      0
    )
  );

  insert into public.workspace_change_log (
    user_id,
    resource,
    client_id,
    operation,
    version
  ) values (
    owner_id,
    tg_table_name,
    stable_client_id,
    case when tg_op = 'DELETE' then 'delete' else 'upsert' end,
    entity_version
  );

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

revoke all on function public.record_workspace_change()
  from public, anon, authenticated;

create trigger record_workspace_change
  after insert or update or delete on public.profiles
  for each row execute function public.record_workspace_change();
create trigger record_workspace_change
  after insert or update or delete on public.moments
  for each row execute function public.record_workspace_change();
create trigger record_workspace_change
  after insert or update or delete on public.reflections
  for each row execute function public.record_workspace_change();
create trigger record_workspace_change
  after insert or update or delete on public.goals
  for each row execute function public.record_workspace_change();
create trigger record_workspace_change
  after insert or update or delete on public.habits
  for each row execute function public.record_workspace_change();
create trigger record_workspace_change
  after insert or update or delete on public.habit_checkins
  for each row execute function public.record_workspace_change();

-- Fixed server-side AI rate limit. Clients cannot choose an identity, window,
-- or quota. Old events are pruned opportunistically for the current user.
create or replace function public.reserve_ai_usage_event()
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  event_count integer;
begin
  if current_user_id is null then
    return false;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('ai_usage_events:' || current_user_id::text, 0)
  );

  delete from public.ai_usage_events
  where user_id = current_user_id
    and created_at < now() - interval '24 hours';

  select count(*) into event_count
  from public.ai_usage_events
  where user_id = current_user_id
    and created_at >= now() - interval '1 hour';

  if event_count >= 20 then
    return false;
  end if;

  insert into public.ai_usage_events (user_id) values (current_user_id);
  return true;
end;
$$;

revoke all on function public.reserve_ai_usage_event() from public, anon;
grant execute on function public.reserve_ai_usage_event() to authenticated;

-- Query indexes ----------------------------------------------------------------

create index moments_history_idx
  on public.moments(user_id, occurred_on desc, created_at desc, client_id desc);
create index reflections_history_idx
  on public.reflections(user_id, updated_at desc, client_id desc);
create index goals_open_order_idx
  on public.goals(user_id, sort_order, created_at desc, client_id)
  where completed_at is null;
create index goals_completed_history_idx
  on public.goals(user_id, completed_at desc, client_id)
  where completed_at is not null;
create index goals_due_date_idx
  on public.goals(user_id, due_date, client_id);
create index habits_history_idx
  on public.habits(user_id, created_at desc, client_id);
create index habit_checkins_user_history_idx
  on public.habit_checkins(user_id, checked_on desc, client_id);
create index habit_checkins_habit_history_idx
  on public.habit_checkins(habit_id, checked_on desc);
create index ai_usage_events_user_created_at_idx
  on public.ai_usage_events(user_id, created_at desc);
create index workspace_change_log_pull_idx
  on public.workspace_change_log(user_id, resource, sequence);

-- Row Level Security -----------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.moments enable row level security;
alter table public.reflections enable row level security;
alter table public.goals enable row level security;
alter table public.habits enable row level security;
alter table public.habit_checkins enable row level security;
alter table public.ai_usage_events enable row level security;
alter table public.workspace_change_log enable row level security;

create policy "Users can view own profile"
  on public.profiles for select using ((select auth.uid()) = user_id);
create policy "Users can insert own profile"
  on public.profiles for insert with check ((select auth.uid()) = user_id);
create policy "Users can update own profile"
  on public.profiles for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can select own moments"
  on public.moments for select using ((select auth.uid()) = user_id);
create policy "Users can insert own moments"
  on public.moments for insert with check ((select auth.uid()) = user_id);
create policy "Users can update own moments"
  on public.moments for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete own moments"
  on public.moments for delete using ((select auth.uid()) = user_id);

create policy "Users can select own reflections"
  on public.reflections for select using ((select auth.uid()) = user_id);
create policy "Users can insert own reflections"
  on public.reflections for insert with check ((select auth.uid()) = user_id);
create policy "Users can update own reflections"
  on public.reflections for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete own reflections"
  on public.reflections for delete using ((select auth.uid()) = user_id);

create policy "Users can select own goals"
  on public.goals for select using ((select auth.uid()) = user_id);
create policy "Users can insert own goals"
  on public.goals for insert with check ((select auth.uid()) = user_id);
create policy "Users can update own goals"
  on public.goals for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete own goals"
  on public.goals for delete using ((select auth.uid()) = user_id);

create policy "Users can select own habits"
  on public.habits for select using ((select auth.uid()) = user_id);
create policy "Users can insert own habits"
  on public.habits for insert with check ((select auth.uid()) = user_id);
create policy "Users can update own habits"
  on public.habits for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete own habits"
  on public.habits for delete using ((select auth.uid()) = user_id);

create policy "Users can select own habit checkins"
  on public.habit_checkins for select using ((select auth.uid()) = user_id);
create policy "Users can insert own habit checkins"
  on public.habit_checkins for insert with check ((select auth.uid()) = user_id);
create policy "Users can update own habit checkins"
  on public.habit_checkins for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete own habit checkins"
  on public.habit_checkins for delete using ((select auth.uid()) = user_id);

create policy "Users can select own AI usage events"
  on public.ai_usage_events for select using ((select auth.uid()) = user_id);

create policy "Users can pull own workspace changes"
  on public.workspace_change_log for select
  using ((select auth.uid()) = user_id);

revoke all on public.workspace_change_log from anon, authenticated;
grant select on public.workspace_change_log to authenticated;

-- Storage ---------------------------------------------------------------------

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'moments',
  'moments',
  false,
  5242880,
  array['image/jpeg', 'image/pjpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Users can read own moment images"
  on storage.objects for select
  using (
    bucket_id = 'moments'
    and (select auth.uid())::text = (storage.foldername(name))[1]
  );
create policy "Users can upload own moment images"
  on storage.objects for insert
  with check (
    bucket_id = 'moments'
    and (select auth.uid())::text = (storage.foldername(name))[1]
  );
create policy "Users can update own moment images"
  on storage.objects for update
  using (
    bucket_id = 'moments'
    and (select auth.uid())::text = (storage.foldername(name))[1]
  )
  with check (
    bucket_id = 'moments'
    and (select auth.uid())::text = (storage.foldername(name))[1]
  );
create policy "Users can delete own moment images"
  on storage.objects for delete
  using (
    bucket_id = 'moments'
    and (select auth.uid())::text = (storage.foldername(name))[1]
  );

notify pgrst, 'reload schema';
