-- Habit check-in history for BulletAI.
-- Run this in Supabase SQL editor or through your migration pipeline before using the new habit UI.

alter table public.habits
  add column if not exists frequency text default 'daily';

update public.habits
set frequency = case
  when frequency in ('weekly', 'Weekly', '每周') then 'weekly'
  else 'daily'
end
where frequency is distinct from case
  when frequency in ('weekly', 'Weekly', '每周') then 'weekly'
  else 'daily'
end;

alter table public.habits
  alter column frequency set default 'daily';

alter table public.habits
  drop constraint if exists habits_frequency_check;

alter table public.habits
  add constraint habits_frequency_check check (frequency in ('daily', 'weekly'));

create table if not exists public.habit_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  habit_id bigint not null references public.habits(id) on delete cascade,
  checked_on date not null,
  created_at timestamptz not null default now(),
  unique(user_id, habit_id, checked_on)
);

create index if not exists habit_checkins_user_checked_on_idx
  on public.habit_checkins(user_id, checked_on desc);

create index if not exists habit_checkins_habit_checked_on_idx
  on public.habit_checkins(habit_id, checked_on desc);

insert into public.habit_checkins (user_id, habit_id, checked_on, created_at)
select
  user_id,
  id,
  last_checkin::date,
  coalesce(last_checkin, now())
from public.habits
where last_checkin is not null
on conflict (user_id, habit_id, checked_on) do nothing;

alter table public.habit_checkins enable row level security;

drop policy if exists "Users can select own habit checkins" on public.habit_checkins;
create policy "Users can select own habit checkins"
  on public.habit_checkins
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own habit checkins" on public.habit_checkins;
create policy "Users can insert own habit checkins"
  on public.habit_checkins
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own habit checkins" on public.habit_checkins;
create policy "Users can delete own habit checkins"
  on public.habit_checkins
  for delete
  using (auth.uid() = user_id);
