-- BulletAI reliability guard migration.
-- Safe to run repeatedly on deployments that predate 000_current_schema.sql.

alter table public.profiles
  add column if not exists username text,
  add column if not exists preferred_language text default 'zh',
  add column if not exists ui_theme text default 'calm',
  add column if not exists accent_color text default 'sage',
  add column if not exists color_scheme text default 'system',
  add column if not exists completed_goal_retention text default 'next_day',
  add column if not exists week_starts_on text default 'auto',
  add column if not exists username_updated_at timestamptz,
  add column if not exists preferences_updated_at timestamptz,
  add column if not exists updated_at timestamptz default timezone('utc'::text, now());

alter table public.moments
  add column if not exists client_id text,
  add column if not exists image_path text,
  add column if not exists updated_at timestamptz default timezone('utc'::text, now()),
  add column if not exists deleted_at timestamptz;

alter table public.reflections
  add column if not exists client_id text,
  add column if not exists title text,
  add column if not exists body text,
  add column if not exists source text,
  add column if not exists source_type text,
  add column if not exists location text,
  add column if not exists image_path text,
  add column if not exists updated_at timestamptz default timezone('utc'::text, now()),
  add column if not exists deleted_at timestamptz;

alter table public.goals
  add column if not exists client_id text,
  add column if not exists description text,
  add column if not exists status text,
  add column if not exists due_date date,
  add column if not exists progress int,
  add column if not exists image_path text,
  add column if not exists color text,
  add column if not exists sort_order double precision,
  add column if not exists updated_at timestamptz default timezone('utc'::text, now()),
  add column if not exists deleted_at timestamptz;

alter table public.habits
  add column if not exists client_id text,
  add column if not exists description text,
  add column if not exists frequency text,
  add column if not exists color text,
  add column if not exists image_path text,
  add column if not exists last_checkin timestamptz,
  add column if not exists checkin_count int default 0,
  add column if not exists updated_at timestamptz default timezone('utc'::text, now()),
  add column if not exists deleted_at timestamptz;

create table if not exists public.habit_checkins (
  id bigint generated by default as identity primary key,
  habit_id bigint references public.habits(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  checked_on date not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.habit_checkins
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists habit_id bigint references public.habits(id) on delete cascade,
  add column if not exists client_id text,
  add column if not exists habit_client_id text,
  add column if not exists checked_on date,
  add column if not exists checked boolean default true,
  add column if not exists updated_at timestamptz default timezone('utc'::text, now()),
  add column if not exists deleted_at timestamptz;

update public.profiles
set
  preferred_language = coalesce(preferred_language, 'zh'),
  ui_theme = coalesce(ui_theme, 'calm'),
  accent_color = coalesce(accent_color, 'sage'),
  color_scheme = coalesce(color_scheme, 'system'),
  completed_goal_retention = coalesce(completed_goal_retention, 'next_day'),
  week_starts_on = case
    when week_starts_on in ('auto', 'monday', 'sunday', 'saturday') then week_starts_on
    else 'auto'
  end,
  updated_at = coalesce(updated_at, timezone('utc'::text, now()))
where true;

update public.moments
set client_id = coalesce(nullif(client_id, ''), 'moment-' || id::text)
where client_id is null or client_id = '';

update public.reflections
set client_id = coalesce(nullif(client_id, ''), 'reflection-' || id::text)
where client_id is null or client_id = '';

update public.goals
set
  client_id = coalesce(nullif(client_id, ''), 'goal-' || id::text),
  description = coalesce(description, ''),
  status = coalesce(status, 'pending'),
  progress = coalesce(progress, 0),
  sort_order = coalesce(sort_order, -extract(epoch from created_at))
where client_id is null
  or client_id = ''
  or description is null
  or status is null
  or progress is null
  or sort_order is null;

update public.habits
set
  client_id = coalesce(nullif(client_id, ''), 'habit-' || id::text),
  frequency = coalesce(frequency, 'daily'),
  checkin_count = coalesce(checkin_count, 0)
where client_id is null
  or client_id = ''
  or frequency is null
  or checkin_count is null;

update public.habit_checkins checkins
set
  client_id = coalesce(checkins.client_id, 'habit-checkin-' || checkins.id::text),
  habit_client_id = coalesce(checkins.habit_client_id, habits.client_id),
  checked = coalesce(checkins.checked, true),
  updated_at = coalesce(checkins.updated_at, checkins.created_at, timezone('utc'::text, now()))
from public.habits habits
where checkins.habit_id = habits.id
  and (
    checkins.client_id is null
    or checkins.habit_client_id is null
    or checkins.checked is null
    or checkins.updated_at is null
  );

insert into public.habit_checkins (
  user_id,
  habit_id,
  client_id,
  habit_client_id,
  checked_on,
  checked,
  created_at,
  updated_at
)
select
  habits.user_id,
  habits.id,
  'habit-checkin-legacy-' || habits.id::text || '-' || habits.last_checkin::date::text,
  habits.client_id,
  habits.last_checkin::date,
  true,
  coalesce(habits.last_checkin, timezone('utc'::text, now())),
  coalesce(habits.last_checkin, timezone('utc'::text, now()))
from public.habits habits
where habits.last_checkin is not null
  and not exists (
    select 1
    from public.habit_checkins checkins
    where checkins.user_id = habits.user_id
      and checkins.habit_id = habits.id
      and checkins.checked_on = habits.last_checkin::date
  );

delete from public.habit_checkins a
using public.habit_checkins b
where a.id > b.id
  and a.user_id = b.user_id
  and a.habit_id = b.habit_id
  and a.checked_on = b.checked_on;

create unique index if not exists moments_client_id_idx on public.moments(client_id);
create unique index if not exists reflections_client_id_idx on public.reflections(client_id);
create unique index if not exists goals_client_id_idx on public.goals(client_id);
create unique index if not exists habits_client_id_idx on public.habits(client_id);
create unique index if not exists habit_checkins_client_id_idx on public.habit_checkins(client_id);
create index if not exists moments_user_id_idx on public.moments(user_id);
create index if not exists reflections_user_id_idx on public.reflections(user_id);
create index if not exists goals_user_id_idx on public.goals(user_id);
create index if not exists goals_user_sort_order_idx on public.goals(user_id, sort_order);
create index if not exists habits_user_id_idx on public.habits(user_id);
create index if not exists habit_checkins_user_checked_on_idx
  on public.habit_checkins(user_id, checked_on desc);
create index if not exists habit_checkins_habit_checked_on_idx
  on public.habit_checkins(habit_id, checked_on desc);

alter table public.habit_checkins drop constraint if exists habit_checkins_user_habit_day_unique;
alter table public.habit_checkins
  add constraint habit_checkins_user_habit_day_unique
  unique (user_id, habit_client_id, checked_on);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'habit_checkins_habit_client_id_fkey'
  ) then
    alter table public.habit_checkins
      add constraint habit_checkins_habit_client_id_fkey
      foreign key (habit_client_id) references public.habits(client_id) on delete cascade;
  end if;
end $$;

create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists ai_usage_events_user_created_at_idx
  on public.ai_usage_events(user_id, created_at desc);

create or replace function public.reserve_ai_usage_event(
  p_user_id uuid,
  p_window_start timestamptz,
  p_limit int
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  event_count int;
begin
  if auth.uid() is null or auth.uid() <> p_user_id then
    return false;
  end if;

  select count(*) into event_count
  from public.ai_usage_events
  where user_id = p_user_id
    and created_at >= p_window_start;

  if event_count >= p_limit then
    return false;
  end if;

  insert into public.ai_usage_events (user_id)
  values (p_user_id);

  return true;
end;
$$;

grant execute on function public.reserve_ai_usage_event(uuid, timestamptz, int)
  to authenticated;

create or replace function public.resolve_habit_checkin_reference()
returns trigger as $$
begin
  if new.habit_client_id is null and new.habit_id is not null then
    select client_id into new.habit_client_id
    from public.habits
    where id = new.habit_id and user_id = new.user_id;
  end if;

  if new.habit_client_id is not null then
    select id into new.habit_id
    from public.habits
    where client_id = new.habit_client_id and user_id = new.user_id;
  end if;

  return new;
end;
$$ language plpgsql;

drop trigger if exists resolve_habit_checkin_reference on public.habit_checkins;
create trigger resolve_habit_checkin_reference
  before insert or update on public.habit_checkins
  for each row execute function public.resolve_habit_checkin_reference();

create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists update_profiles_updated_at on public.profiles;
create trigger update_profiles_updated_at
  before update on public.profiles
  for each row
  execute function public.update_updated_at_column();

drop trigger if exists update_moments_updated_at on public.moments;
create trigger update_moments_updated_at
  before update on public.moments
  for each row
  execute function public.update_updated_at_column();

drop trigger if exists update_reflections_updated_at on public.reflections;
create trigger update_reflections_updated_at
  before update on public.reflections
  for each row
  execute function public.update_updated_at_column();

drop trigger if exists update_goals_updated_at on public.goals;
create trigger update_goals_updated_at
  before update on public.goals
  for each row
  execute function public.update_updated_at_column();

drop trigger if exists update_habits_updated_at on public.habits;
create trigger update_habits_updated_at
  before update on public.habits
  for each row
  execute function public.update_updated_at_column();

drop trigger if exists update_habit_checkins_updated_at on public.habit_checkins;
create trigger update_habit_checkins_updated_at
  before update on public.habit_checkins
  for each row
  execute function public.update_updated_at_column();

alter table public.profiles enable row level security;
alter table public.moments enable row level security;
alter table public.reflections enable row level security;
alter table public.goals enable row level security;
alter table public.habits enable row level security;
alter table public.habit_checkins enable row level security;
alter table public.ai_usage_events enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
  on public.profiles for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can select own moments" on public.moments;
create policy "Users can select own moments"
  on public.moments for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own moments" on public.moments;
create policy "Users can insert own moments"
  on public.moments for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own moments" on public.moments;
create policy "Users can update own moments"
  on public.moments for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own moments" on public.moments;
create policy "Users can delete own moments"
  on public.moments for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can select own reflections" on public.reflections;
create policy "Users can select own reflections"
  on public.reflections for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own reflections" on public.reflections;
create policy "Users can insert own reflections"
  on public.reflections for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own reflections" on public.reflections;
create policy "Users can update own reflections"
  on public.reflections for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own reflections" on public.reflections;
create policy "Users can delete own reflections"
  on public.reflections for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can select own goals" on public.goals;
create policy "Users can select own goals"
  on public.goals for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own goals" on public.goals;
create policy "Users can insert own goals"
  on public.goals for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own goals" on public.goals;
create policy "Users can update own goals"
  on public.goals for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own goals" on public.goals;
create policy "Users can delete own goals"
  on public.goals for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can select own habits" on public.habits;
create policy "Users can select own habits"
  on public.habits for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own habits" on public.habits;
create policy "Users can insert own habits"
  on public.habits for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own habits" on public.habits;
create policy "Users can update own habits"
  on public.habits for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own habits" on public.habits;
create policy "Users can delete own habits"
  on public.habits for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can select own habit checkins" on public.habit_checkins;
create policy "Users can select own habit checkins"
  on public.habit_checkins for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own habit checkins" on public.habit_checkins;
create policy "Users can insert own habit checkins"
  on public.habit_checkins for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own habit checkins" on public.habit_checkins;
create policy "Users can update own habit checkins"
  on public.habit_checkins for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own habit checkins" on public.habit_checkins;
create policy "Users can delete own habit checkins"
  on public.habit_checkins for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can select own AI usage events" on public.ai_usage_events;
create policy "Users can select own AI usage events"
  on public.ai_usage_events for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own AI usage events" on public.ai_usage_events;
create policy "Users can insert own AI usage events"
  on public.ai_usage_events for insert
  with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values
  ('moments', 'moments', false),
  ('reflections', 'reflections', false),
  ('goals', 'goals', false),
  ('habits', 'habits', false)
on conflict (id) do nothing;

drop policy if exists "Users can read own stored files" on storage.objects;
create policy "Users can read own stored files"
  on storage.objects for select
  using (
    bucket_id in ('moments', 'reflections', 'goals', 'habits')
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Users can upload own stored files" on storage.objects;
create policy "Users can upload own stored files"
  on storage.objects for insert
  with check (
    bucket_id in ('moments', 'reflections', 'goals', 'habits')
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Users can update own stored files" on storage.objects;
create policy "Users can update own stored files"
  on storage.objects for update
  using (
    bucket_id in ('moments', 'reflections', 'goals', 'habits')
    and auth.uid()::text = (storage.foldername(name))[1]
  )
  with check (
    bucket_id in ('moments', 'reflections', 'goals', 'habits')
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Users can delete own stored files" on storage.objects;
create policy "Users can delete own stored files"
  on storage.objects for delete
  using (
    bucket_id in ('moments', 'reflections', 'goals', 'habits')
    and auth.uid()::text = (storage.foldername(name))[1]
  );

notify pgrst, 'reload schema';
