-- Minimal post-004 legacy shape used to prove the documented 005 + 006
-- upgrade path. Supabase-owned auth/storage schemas are created by the local
-- stack before this fixture is loaded.

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text,
  preferred_language text default 'zh',
  ui_theme text default 'calm',
  accent_color text default 'sage',
  color_scheme text default 'system',
  completed_goal_retention text default 'next_day',
  week_starts_on text default 'auto',
  username_updated_at timestamptz,
  preferences_updated_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.moments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text,
  content text,
  image_path text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz
);

create table public.reflections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text,
  content text,
  title text,
  body text,
  source text,
  source_type text,
  location text,
  image_path text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz
);

create table public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text,
  title text,
  description text,
  status text default 'pending',
  due_date date,
  progress integer default 0,
  image_path text,
  color text,
  sort_order double precision,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz
);

create table public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text,
  name text,
  description text,
  frequency text default 'daily',
  color text,
  image_path text,
  last_checkin timestamptz,
  checkin_count integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz
);

create table public.habit_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  habit_id bigint references public.habits(id) on delete cascade,
  client_id text,
  habit_client_id text,
  checked_on date,
  checked boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz
);

create table public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

grant select, insert, update, delete on
  public.profiles,
  public.moments,
  public.reflections,
  public.goals,
  public.habits,
  public.habit_checkins,
  public.ai_usage_events
to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into auth.users (id, email)
values (
  '80000000-0000-0000-0000-000000000008',
  'legacy-upgrade@example.com'
);

insert into public.profiles (
  user_id,
  username,
  preferred_language,
  accent_color,
  color_scheme,
  completed_goal_retention,
  week_starts_on
) values (
  '80000000-0000-0000-0000-000000000008',
  '  Legacy User  ',
  'invalid',
  'invalid',
  'invalid',
  'invalid',
  'invalid'
);

insert into public.moments (
  user_id,
  client_id,
  content,
  created_at,
  deleted_at
) values
  (
    '80000000-0000-0000-0000-000000000008',
    null,
    'Retained legacy moment',
    timestamptz '2024-02-03 10:00:00+00',
    null
  ),
  (
    '80000000-0000-0000-0000-000000000008',
    'deleted-legacy-moment',
    'Deleted legacy moment',
    timestamptz '2024-02-04 10:00:00+00',
    timestamptz '2024-02-05 10:00:00+00'
  );

insert into public.reflections (user_id, content, title, body, created_at)
values (
  '80000000-0000-0000-0000-000000000008',
  E'Legacy title\n\nLegacy body',
  'Legacy title',
  'Legacy body',
  timestamptz '2024-02-04 10:00:00+00'
);

insert into public.goals (
  user_id,
  title,
  status,
  progress,
  created_at,
  updated_at
) values (
  '80000000-0000-0000-0000-000000000008',
  'Legacy completed goal',
  'completed',
  100,
  timestamptz '2024-02-05 10:00:00+00',
  timestamptz '2024-02-06 10:00:00+00'
);

insert into public.habits (
  user_id,
  name,
  frequency,
  last_checkin,
  created_at
) values (
  '80000000-0000-0000-0000-000000000008',
  'Legacy habit',
  'Weekly',
  timestamptz '2024-02-08 08:00:00+00',
  timestamptz '2024-02-07 08:00:00+00'
);
